; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_ldf_mode  = deep+

[env:main]
build_src_filter = -<*> +<main_code/>
lib_deps = 
	arduino-libraries/Servo@^1.3.0
	paulstoffregen/Encoder@^1.4.4
	feilipu/FreeRTOS@^11.1.0-3

[env:test_encoder]
build_src_filter = -<*> +<test_encoder/>
lib_deps = 
	paulstoffregen/Encoder@^1.4.4
	feilipu/FreeRTOS@^11.1.0-3

[env:test_servo]
build_src_filter = -<*> +<test_servo/>
lib_deps = 
	arduino-libraries/Servo@^1.3.0
	feilipu/FreeRTOS@^11.1.0-3


[env:test_step]
build_src_filter = -<*> +<test_step/>
monitor_filters = log2file
lib_deps = 
	arduino-libraries/Servo@^1.3.0
	paulstoffregen/Encoder@^1.4.4
	feilipu/FreeRTOS@^11.1.0-3
